/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 */

import type { DailyConnectionEndpoint } from '@pipecat-ai/daily-transport';

type SmallWebRTCConfig = {
  webrtcRequestParams: {
    endpoint: string;
  };
};

type TransportConfig = DailyConnectionEndpoint | SmallWebRTCConfig;

export type TransportType = 'daily' | 'smallwebrtc';

export const AVAILABLE_TRANSPORTS: TransportType[] = [
  'smallwebrtc',
  'daily',
];

export const DEFAULT_TRANSPORT: TransportType = 'smallwebrtc';

const configuredServerOrigin =
  import.meta.env.VITE_PIPECAT_SERVER_ORIGIN ||
  import.meta.env.VITE_BOT_SERVER_ORIGIN ||
  import.meta.env.VITE_SERVER_ORIGIN ||
  'http://52.146.8.205:7860';

const serverOrigin = configuredServerOrigin.replace(/\/$/, '');

if (!import.meta.env.VITE_PIPECAT_SERVER_ORIGIN) {
  console.warn(
    `PIPECAT server origin not configured, using default: ${serverOrigin}`
  );
}

const botStartUrl =
  import.meta.env.VITE_BOT_START_URL || `${serverOrigin}/start`;
const botStartPublicApiKey = import.meta.env.VITE_BOT_START_PUBLIC_API_KEY;

if (!import.meta.env.VITE_BOT_START_URL) {
  console.warn(`VITE_BOT_START_URL not configured, using: ${botStartUrl}`);
}

const smallWebRTCRequestEndpoint =
  import.meta.env.VITE_SMALL_WEBRTC_ENDPOINT ||
  `${serverOrigin}/api/offer`;

const dailyConfig: DailyConnectionEndpoint = {
  endpoint: botStartUrl,
  requestData: {
    createDailyRoom: true,
    dailyRoomProperties: { start_video_off: true },
  },
};

if (botStartPublicApiKey) {
  dailyConfig.headers = new Headers({
    Authorization: `Bearer ${botStartPublicApiKey}`,
  });
}

export const TRANSPORT_CONFIG: Record<TransportType, TransportConfig> = {
  daily: dailyConfig,
  smallwebrtc: {
    webrtcRequestParams: { endpoint: smallWebRTCRequestEndpoint },
  },
};
